# Generated by Django 5.1.6 on 2025-02-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the campaign')),
                ('campaign_type', models.CharField(choices=[('BOGO', 'Buy One Get One Free'), ('THRESHOLD', 'Threshold Discount')], help_text='Type of campaign', max_length=20)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount required for discount (for threshold campaigns)', max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount applied if threshold is met (for threshold campaigns)', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether the campaign is active')),
                ('start_date', models.DateTimeField(blank=True, help_text='Campaign start time', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Campaign end time', null=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Products applicable for this campaign', to='products.product')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['name'],
            },
        ),
    ]
