# Generated by Django 5.1.6 on 2025-02-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the store name.', max_length=150, unique=True)),
                ('address', models.CharField(help_text='Enter the full address of the store.', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Enter the contact phone number.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter the contact email address.', max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geolocation (optional).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geolocation (optional).', max_digits=9, null=True)),
                ('active', models.BooleanField(default=True, help_text='Designates whether this store is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the store was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the store was last updated.')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
    ]
