# Generated by Django 5.1.6 on 2025-02-16 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0002_storeinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total sale amount', max_digits=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('other', 'Other')], help_text='Type of payment', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of the sale')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign applied to the sale (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('sales_rep', models.ForeignKey(blank=True, help_text='Sales representative who made the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(help_text='Store where the sale occurred', on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity sold')),
                ('price_per_item', models.DecimalField(decimal_places=2, help_text='Unit price at the time of sale', max_digits=10)),
                ('campaign_applied', models.BooleanField(default=False, help_text='Indicates if campaign pricing was applied')),
                ('product_variant', models.ForeignKey(help_text='Sold product variant', on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('sale', models.ForeignKey(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
