# Generated by Django 5.1.6 on 2025-02-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Shoes, Bags, Clothing)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Color name (e.g., Red, Blue, Black)', max_length=50, unique=True)),
                ('hex_value', models.CharField(blank=True, help_text='Hex code for the color (e.g., #FF0000)', max_length=7)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size label (e.g., S, M, L, XL or numeric for shoes)', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('barcode', models.CharField(blank=True, help_text='Unique barcode if available', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('brand', models.CharField(blank=True, help_text='Brand of the product', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', help_text='Target gender for the product', max_length=10)),
                ('category', models.ForeignKey(help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price for this variant', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock for this variant')),
                ('color', models.ForeignKey(blank=True, help_text='Variant color', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('product', models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('size', models.ForeignKey(blank=True, help_text='Variant size', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
